// Generated by `wit-bindgen` 0.48.1. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod tegmentum {
    pub mod compression_multiplexer {
      /// Compression dispatcher interface
      ///
      /// This interface allows Layer 2 components (ZIP, TAR, etc.) to select
      /// compression algorithms at runtime instead of being locked to a single
      /// algorithm at build time.
      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod compression_dispatcher {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        /// Compression algorithm selection
        #[repr(u8)]
        #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
        pub enum Algorithm {
          /// No compression (pass-through)
          Store,
          /// DEFLATE compression (RFC 1951)
          Deflate,
          /// BZIP2 compression
          Bzip2,
          /// LZMA compression
          Lzma,
          /// Zstandard compression
          Zstd,
          /// LZ4 compression (extremely fast)
          Lz4,
          /// OpenZL compression (Meta's format-aware compression)
          Openzl,
        }
        impl ::core::fmt::Debug for Algorithm {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              Algorithm::Store => {
                f.debug_tuple("Algorithm::Store").finish()
              }
              Algorithm::Deflate => {
                f.debug_tuple("Algorithm::Deflate").finish()
              }
              Algorithm::Bzip2 => {
                f.debug_tuple("Algorithm::Bzip2").finish()
              }
              Algorithm::Lzma => {
                f.debug_tuple("Algorithm::Lzma").finish()
              }
              Algorithm::Zstd => {
                f.debug_tuple("Algorithm::Zstd").finish()
              }
              Algorithm::Lz4 => {
                f.debug_tuple("Algorithm::Lz4").finish()
              }
              Algorithm::Openzl => {
                f.debug_tuple("Algorithm::Openzl").finish()
              }
            }
          }
        }

        impl Algorithm{
          #[doc(hidden)]
          pub unsafe fn _lift(val: u8) -> Algorithm{
            if !cfg!(debug_assertions) {
              return unsafe { ::core::mem::transmute(val) };
            }

            match val {
              0 => Algorithm::Store,
              1 => Algorithm::Deflate,
              2 => Algorithm::Bzip2,
              3 => Algorithm::Lzma,
              4 => Algorithm::Zstd,
              5 => Algorithm::Lz4,
              6 => Algorithm::Openzl,

              _ => panic!("invalid enum discriminant"),
            }
          }
        }

        /// Compressor resource

        #[derive(Debug)]
        #[repr(transparent)]
        pub struct Compressor{
          handle: _rt::Resource<Compressor>,
        }

        type _CompressorRep<T> = Option<T>;

        impl Compressor{
          /// Creates a new resource from the specified representation.
          ///
          /// This function will create a new resource handle by moving `val` onto
          /// the heap and then passing that heap pointer to the component model to
          /// create a handle. The owned handle is then returned as `Compressor`.
          pub fn new<T: GuestCompressor>(val: T) -> Self {
            Self::type_guard::<T>();
            let val: _CompressorRep<T> = Some(val);
            let ptr: *mut _CompressorRep<T> =
            _rt::Box::into_raw(_rt::Box::new(val));
            unsafe {
              Self::from_handle(T::_resource_new(ptr.cast()))
            }
          }

          /// Gets access to the underlying `T` which represents this resource.
          pub fn get<T: GuestCompressor>(&self) -> &T {
            let ptr = unsafe { &*self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          /// Gets mutable access to the underlying `T` which represents this
          /// resource.
          pub fn get_mut<T: GuestCompressor>(&mut self) -> &mut T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_mut().unwrap()
          }

          /// Consumes this resource and returns the underlying `T`.
          pub fn into_inner<T: GuestCompressor>(self) -> T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.take().unwrap()
          }

          #[doc(hidden)]
          pub unsafe fn from_handle(handle: u32) -> Self {
            Self {
              handle: unsafe { _rt::Resource::from_handle(handle) },
            }
          }

          #[doc(hidden)]
          pub fn take_handle(&self) -> u32 {
            _rt::Resource::take_handle(&self.handle)
          }

          #[doc(hidden)]
          pub fn handle(&self) -> u32 {
            _rt::Resource::handle(&self.handle)
          }

          // It's theoretically possible to implement the `GuestCompressor` trait twice
          // so guard against using it with two different types here.
          #[doc(hidden)]
          fn type_guard<T: 'static>() {
            use core::any::TypeId;
            static mut LAST_TYPE: Option<TypeId> = None;
            unsafe {
              assert!(!cfg!(target_feature = "atomics"));
              let id = TypeId::of::<T>();
              match LAST_TYPE {
                Some(ty) => assert!(ty == id, "cannot use two types with this resource type"),
                None => LAST_TYPE = Some(id),
              }
            }
          }

          #[doc(hidden)]
          pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
            Self::type_guard::<T>();
            let _ = unsafe { _rt::Box::from_raw(handle as *mut _CompressorRep<T>) };
          }

          fn as_ptr<T: GuestCompressor>(&self) -> *mut _CompressorRep<T> {
            Compressor::type_guard::<T>();
            T::_resource_rep(self.handle()).cast()
          }
        }

        /// A borrowed version of [`Compressor`] which represents a borrowed value
        /// with the lifetime `'a`.
        #[derive(Debug)]
        #[repr(transparent)]
        pub struct CompressorBorrow<'a> {
          rep: *mut u8,
          _marker: core::marker::PhantomData<&'a Compressor>,
        }

        impl<'a> CompressorBorrow<'a>{
          #[doc(hidden)]
          pub unsafe fn lift(rep: usize) -> Self {
            Self {
              rep: rep as *mut u8,
              _marker: core::marker::PhantomData,
            }
          }

          /// Gets access to the underlying `T` in this resource.
          pub fn get<T: GuestCompressor>(&self) -> &'a T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          // NB: mutable access is not allowed due to the component model allowing
          // multiple borrows of the same resource.

          fn as_ptr<T: 'static>(&self) -> *mut _CompressorRep<T> {
            Compressor::type_guard::<T>();
            self.rep.cast()
          }
        }
        

        unsafe impl _rt::WasmResource for Compressor{
          #[inline]
          unsafe fn drop(_handle: u32) {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]tegmentum:compression-multiplexer/compression-dispatcher@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]compressor"]
              fn drop(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
            
            unsafe { drop(_handle as i32); }
          }
        }
        
        /// Decompressor resource

        #[derive(Debug)]
        #[repr(transparent)]
        pub struct Decompressor{
          handle: _rt::Resource<Decompressor>,
        }

        type _DecompressorRep<T> = Option<T>;

        impl Decompressor{
          /// Creates a new resource from the specified representation.
          ///
          /// This function will create a new resource handle by moving `val` onto
          /// the heap and then passing that heap pointer to the component model to
          /// create a handle. The owned handle is then returned as `Decompressor`.
          pub fn new<T: GuestDecompressor>(val: T) -> Self {
            Self::type_guard::<T>();
            let val: _DecompressorRep<T> = Some(val);
            let ptr: *mut _DecompressorRep<T> =
            _rt::Box::into_raw(_rt::Box::new(val));
            unsafe {
              Self::from_handle(T::_resource_new(ptr.cast()))
            }
          }

          /// Gets access to the underlying `T` which represents this resource.
          pub fn get<T: GuestDecompressor>(&self) -> &T {
            let ptr = unsafe { &*self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          /// Gets mutable access to the underlying `T` which represents this
          /// resource.
          pub fn get_mut<T: GuestDecompressor>(&mut self) -> &mut T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_mut().unwrap()
          }

          /// Consumes this resource and returns the underlying `T`.
          pub fn into_inner<T: GuestDecompressor>(self) -> T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.take().unwrap()
          }

          #[doc(hidden)]
          pub unsafe fn from_handle(handle: u32) -> Self {
            Self {
              handle: unsafe { _rt::Resource::from_handle(handle) },
            }
          }

          #[doc(hidden)]
          pub fn take_handle(&self) -> u32 {
            _rt::Resource::take_handle(&self.handle)
          }

          #[doc(hidden)]
          pub fn handle(&self) -> u32 {
            _rt::Resource::handle(&self.handle)
          }

          // It's theoretically possible to implement the `GuestDecompressor` trait twice
          // so guard against using it with two different types here.
          #[doc(hidden)]
          fn type_guard<T: 'static>() {
            use core::any::TypeId;
            static mut LAST_TYPE: Option<TypeId> = None;
            unsafe {
              assert!(!cfg!(target_feature = "atomics"));
              let id = TypeId::of::<T>();
              match LAST_TYPE {
                Some(ty) => assert!(ty == id, "cannot use two types with this resource type"),
                None => LAST_TYPE = Some(id),
              }
            }
          }

          #[doc(hidden)]
          pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
            Self::type_guard::<T>();
            let _ = unsafe { _rt::Box::from_raw(handle as *mut _DecompressorRep<T>) };
          }

          fn as_ptr<T: GuestDecompressor>(&self) -> *mut _DecompressorRep<T> {
            Decompressor::type_guard::<T>();
            T::_resource_rep(self.handle()).cast()
          }
        }

        /// A borrowed version of [`Decompressor`] which represents a borrowed value
        /// with the lifetime `'a`.
        #[derive(Debug)]
        #[repr(transparent)]
        pub struct DecompressorBorrow<'a> {
          rep: *mut u8,
          _marker: core::marker::PhantomData<&'a Decompressor>,
        }

        impl<'a> DecompressorBorrow<'a>{
          #[doc(hidden)]
          pub unsafe fn lift(rep: usize) -> Self {
            Self {
              rep: rep as *mut u8,
              _marker: core::marker::PhantomData,
            }
          }

          /// Gets access to the underlying `T` in this resource.
          pub fn get<T: GuestDecompressor>(&self) -> &'a T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          // NB: mutable access is not allowed due to the component model allowing
          // multiple borrows of the same resource.

          fn as_ptr<T: 'static>(&self) -> *mut _DecompressorRep<T> {
            Decompressor::type_guard::<T>();
            self.rep.cast()
          }
        }
        

        unsafe impl _rt::WasmResource for Decompressor{
          #[inline]
          unsafe fn drop(_handle: u32) {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]tegmentum:compression-multiplexer/compression-dispatcher@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]decompressor"]
              fn drop(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
            
            unsafe { drop(_handle as i32); }
          }
        }
        
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_constructor_compressor_cabi<T: GuestCompressor>(arg0: i32,arg1: i32,) -> i32 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result0 = {
          Compressor::new(T::new(Algorithm::_lift(arg0 as u8), arg1 as u8))
        };
        (result0).take_handle() as i32
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_method_compressor_compress_cabi<T: GuestCompressor>(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result1 = {
        let len0 = arg2;
        T::compress(CompressorBorrow::lift(arg0 as u32 as usize).get(), _rt::Vec::from_raw_parts(arg1.cast(), len0, len0))
      };
      let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
      match result1 {
        Ok(e) => { {
          *ptr2.add(0).cast::<u8>() = (0i32) as u8;
          let vec3 = (e).into_boxed_slice();
          let ptr3 = vec3.as_ptr().cast::<u8>();
          let len3 = vec3.len();
          ::core::mem::forget(vec3);
          *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
          *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3.cast_mut();
        } },
        Err(e) => { {
          *ptr2.add(0).cast::<u8>() = (1i32) as u8;
          let vec4 = (e.into_bytes()).into_boxed_slice();
          let ptr4 = vec4.as_ptr().cast::<u8>();
          let len4 = vec4.len();
          ::core::mem::forget(vec4);
          *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
          *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
        } },
      };ptr2
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_method_compressor_compress<T: GuestCompressor>(arg0: *mut u8,) { unsafe {
      let l0 = i32::from(*arg0.add(0).cast::<u8>());
      match l0 {
        0 => {
          let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base3 = l1;
          let len3 = l2;
          _rt::cabi_dealloc(base3, len3 * 1, 1);
        },
        _ => {
          let l4 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l5 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l4, l5, 1);
        },
      }
    } }
    #[doc(hidden)]
    #[allow(non_snake_case, unused_unsafe)]
    pub unsafe fn _export_constructor_decompressor_cabi<T: GuestDecompressor>(arg0: i32,) -> i32 { unsafe {#[cfg(target_arch="wasm32")]
    _rt::run_ctors_once();let result0 = {
      Decompressor::new(T::new(Algorithm::_lift(arg0 as u8)))
    };
    (result0).take_handle() as i32
  } }
  #[doc(hidden)]
  #[allow(non_snake_case, unused_unsafe)]
  pub unsafe fn _export_method_decompressor_decompress_cabi<T: GuestDecompressor>(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
  _rt::run_ctors_once();let result1 = {
    let len0 = arg2;
    T::decompress(DecompressorBorrow::lift(arg0 as u32 as usize).get(), _rt::Vec::from_raw_parts(arg1.cast(), len0, len0))
  };
  let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
  match result1 {
    Ok(e) => { {
      *ptr2.add(0).cast::<u8>() = (0i32) as u8;
      let vec3 = (e).into_boxed_slice();
      let ptr3 = vec3.as_ptr().cast::<u8>();
      let len3 = vec3.len();
      ::core::mem::forget(vec3);
      *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
      *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3.cast_mut();
    } },
    Err(e) => { {
      *ptr2.add(0).cast::<u8>() = (1i32) as u8;
      let vec4 = (e.into_bytes()).into_boxed_slice();
      let ptr4 = vec4.as_ptr().cast::<u8>();
      let len4 = vec4.len();
      ::core::mem::forget(vec4);
      *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
      *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
    } },
  };ptr2
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_decompressor_decompress<T: GuestDecompressor>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base3 = l1;
      let len3 = l2;
      _rt::cabi_dealloc(base3, len3 * 1, 1);
    },
    _ => {
      let l4 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l5 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l4, l5, 1);
    },
  }
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_supported_algorithms_cabi<T: Guest>() -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::supported_algorithms()
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
let vec2 = result0;
let len2 = vec2.len();
let layout2 = _rt::alloc::Layout::from_size_align(vec2.len() * 1, 1).unwrap();
let (result2, _cleanup2) = wit_bindgen::rt::Cleanup::new(layout2);if let Some(cleanup) = _cleanup2 { cleanup.forget(); }
for (i, e) in vec2.into_iter().enumerate() {
  let base = result2.add(i * 1);
  {
    *base.add(0).cast::<u8>() = (e.clone() as i32) as u8;
  }
}
*ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
*ptr1.add(0).cast::<*mut u8>() = result2;
ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_supported_algorithms<T: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = *arg0.add(0).cast::<*mut u8>();
  let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
  let base2 = l0;
  let len2 = l1;
  _rt::cabi_dealloc(base2, len2 * 1, 1);
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_algorithm_info_cabi<T: Guest>(arg0: i32,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::algorithm_info(Algorithm::_lift(arg0 as u8))
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Some(e) => {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    let vec2 = (e.into_bytes()).into_boxed_slice();
    let ptr2 = vec2.as_ptr().cast::<u8>();
    let len2 = vec2.len();
    ::core::mem::forget(vec2);
    *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2.cast_mut();
  },
  None => {
    {
      *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    }
  },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_algorithm_info<T: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => (),
    _ => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l1, l2, 1);
    },
  }
} }
pub trait Guest {
  type Compressor: GuestCompressor;
  type Decompressor: GuestDecompressor;
  /// Get list of supported algorithms
  ///
  /// Returns algorithms available in this multiplexer instance
  #[allow(async_fn_in_trait)]
  fn supported_algorithms() -> _rt::Vec::<Algorithm>;
  /// Get algorithm information
  ///
  /// Returns human-readable description of the algorithm
  #[allow(async_fn_in_trait)]
  fn algorithm_info(algo: Algorithm,) -> Option<_rt::String>;
}
pub trait GuestCompressor: 'static {

  #[doc(hidden)]
  unsafe fn _resource_new(val: *mut u8) -> u32
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]tegmentum:compression-multiplexer/compression-dispatcher@0.1.0")]
    unsafe extern "C" {
      #[link_name = "[resource-new]compressor"]
      fn new(_: *mut u8, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn new(_: *mut u8, ) -> i32 { unreachable!() }
    
    unsafe { new(val) as u32 }
  }

  #[doc(hidden)]
  fn _resource_rep(handle: u32) -> *mut u8
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]tegmentum:compression-multiplexer/compression-dispatcher@0.1.0")]
    unsafe extern "C" {
      #[link_name = "[resource-rep]compressor"]
      fn rep(_: i32, ) -> *mut u8;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn rep(_: i32, ) -> *mut u8 { unreachable!() }
    
    unsafe { rep(handle as i32) }
  }

  
  /// Create a new compressor
  ///
  /// Arguments:
  /// - algo: The compression algorithm to use
  /// - level: Compression level (0-9)
  ///   - 0: No compression (store only) or fastest
  ///   - 1-3: Fast compression
  ///   - 4-6: Balanced (default: 6)
  ///   - 7-9: Maximum compression
  ///
  /// Errors:
  /// - "unsupported-algorithm" if algorithm is not available
  /// - "invalid-level" if level is out of range for algorithm
  #[allow(async_fn_in_trait)]
  fn new(algo: Algorithm,level: u8,) -> Self;
  /// Compress data
  ///
  /// Returns compressed data or error message
  #[allow(async_fn_in_trait)]
  fn compress(&self,input: _rt::Vec::<u8>,) -> Result<_rt::Vec::<u8>,_rt::String>;
}
pub trait GuestDecompressor: 'static {

  #[doc(hidden)]
  unsafe fn _resource_new(val: *mut u8) -> u32
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]tegmentum:compression-multiplexer/compression-dispatcher@0.1.0")]
    unsafe extern "C" {
      #[link_name = "[resource-new]decompressor"]
      fn new(_: *mut u8, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn new(_: *mut u8, ) -> i32 { unreachable!() }
    
    unsafe { new(val) as u32 }
  }

  #[doc(hidden)]
  fn _resource_rep(handle: u32) -> *mut u8
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]tegmentum:compression-multiplexer/compression-dispatcher@0.1.0")]
    unsafe extern "C" {
      #[link_name = "[resource-rep]decompressor"]
      fn rep(_: i32, ) -> *mut u8;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn rep(_: i32, ) -> *mut u8 { unreachable!() }
    
    unsafe { rep(handle as i32) }
  }

  
  /// Create a new decompressor
  ///
  /// The algorithm must match what was used for compression
  #[allow(async_fn_in_trait)]
  fn new(algo: Algorithm,) -> Self;
  /// Decompress data
  ///
  /// Returns decompressed data or error message
  #[allow(async_fn_in_trait)]
  fn decompress(&self,input: _rt::Vec::<u8>,) -> Result<_rt::Vec::<u8>,_rt::String>;
}
#[doc(hidden)]

macro_rules! __export_tegmentum_compression_multiplexer_compression_dispatcher_0_1_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "tegmentum:compression-multiplexer/compression-dispatcher@0.1.0#[constructor]compressor")]
    unsafe extern "C" fn export_constructor_compressor(arg0: i32,arg1: i32,) -> i32 {
      unsafe { $($path_to_types)*::_export_constructor_compressor_cabi::<<$ty as $($path_to_types)*::Guest>::Compressor>(arg0, arg1) }
    }
    #[unsafe(export_name = "tegmentum:compression-multiplexer/compression-dispatcher@0.1.0#[method]compressor.compress")]
    unsafe extern "C" fn export_method_compressor_compress(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_compressor_compress_cabi::<<$ty as $($path_to_types)*::Guest>::Compressor>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "cabi_post_tegmentum:compression-multiplexer/compression-dispatcher@0.1.0#[method]compressor.compress")]
    unsafe extern "C" fn _post_return_method_compressor_compress(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_compressor_compress::<<$ty as $($path_to_types)*::Guest>::Compressor>(arg0) }
    }
    #[unsafe(export_name = "tegmentum:compression-multiplexer/compression-dispatcher@0.1.0#[constructor]decompressor")]
    unsafe extern "C" fn export_constructor_decompressor(arg0: i32,) -> i32 {
      unsafe { $($path_to_types)*::_export_constructor_decompressor_cabi::<<$ty as $($path_to_types)*::Guest>::Decompressor>(arg0) }
    }
    #[unsafe(export_name = "tegmentum:compression-multiplexer/compression-dispatcher@0.1.0#[method]decompressor.decompress")]
    unsafe extern "C" fn export_method_decompressor_decompress(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_decompressor_decompress_cabi::<<$ty as $($path_to_types)*::Guest>::Decompressor>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "cabi_post_tegmentum:compression-multiplexer/compression-dispatcher@0.1.0#[method]decompressor.decompress")]
    unsafe extern "C" fn _post_return_method_decompressor_decompress(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_decompressor_decompress::<<$ty as $($path_to_types)*::Guest>::Decompressor>(arg0) }
    }
    #[unsafe(export_name = "tegmentum:compression-multiplexer/compression-dispatcher@0.1.0#supported-algorithms")]
    unsafe extern "C" fn export_supported_algorithms() -> *mut u8 {
      unsafe { $($path_to_types)*::_export_supported_algorithms_cabi::<$ty>() }
    }
    #[unsafe(export_name = "cabi_post_tegmentum:compression-multiplexer/compression-dispatcher@0.1.0#supported-algorithms")]
    unsafe extern "C" fn _post_return_supported_algorithms(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_supported_algorithms::<$ty>(arg0) }
    }
    #[unsafe(export_name = "tegmentum:compression-multiplexer/compression-dispatcher@0.1.0#algorithm-info")]
    unsafe extern "C" fn export_algorithm_info(arg0: i32,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_algorithm_info_cabi::<$ty>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_tegmentum:compression-multiplexer/compression-dispatcher@0.1.0#algorithm-info")]
    unsafe extern "C" fn _post_return_algorithm_info(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_algorithm_info::<$ty>(arg0) }
    }

    const _: () = {
      #[doc(hidden)]
      #[unsafe(export_name = "tegmentum:compression-multiplexer/compression-dispatcher@0.1.0#[dtor]compressor")]
      #[allow(non_snake_case)]
      unsafe extern "C" fn dtor(rep: *mut u8) {
        unsafe {
          $($path_to_types)*::Compressor::dtor::<
          <$ty as $($path_to_types)*::Guest>::Compressor
          >(rep)
        }
      }
    };
    

    const _: () = {
      #[doc(hidden)]
      #[unsafe(export_name = "tegmentum:compression-multiplexer/compression-dispatcher@0.1.0#[dtor]decompressor")]
      #[allow(non_snake_case)]
      unsafe extern "C" fn dtor(rep: *mut u8) {
        unsafe {
          $($path_to_types)*::Decompressor::dtor::<
          <$ty as $($path_to_types)*::Guest>::Decompressor
          >(rep)
        }
      }
    };
    
  };);
}
#[doc(hidden)]
pub(crate) use __export_tegmentum_compression_multiplexer_compression_dispatcher_0_1_0_cabi;

#[cfg_attr(target_pointer_width="64", repr(align(8)))]
#[cfg_attr(target_pointer_width="32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);

}

}
}
}
mod _rt {
  #![allow(dead_code, clippy::all)]


  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != 0 && handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  pub use alloc_crate::boxed::Box;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  pub use alloc_crate::vec::Vec;
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub use alloc_crate::string::String;
  pub use alloc_crate::alloc;
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_compression_multiplexer_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::tegmentum::compression_multiplexer::compression_dispatcher::__export_tegmentum_compression_multiplexer_compression_dispatcher_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::tegmentum::compression_multiplexer::compression_dispatcher);
  )
}
#[doc(inline)]
pub(crate) use __export_compression_multiplexer_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.48.1:tegmentum:compression-multiplexer@0.1.0:compression-multiplexer:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 655] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x81\x04\x01A\x02\x01\
A\x02\x01B\x18\x01m\x07\x05store\x07deflate\x05bzip2\x04lzma\x04zstd\x03lz4\x06o\
penzl\x04\0\x09algorithm\x03\0\0\x04\0\x0acompressor\x03\x01\x04\0\x0cdecompress\
or\x03\x01\x01i\x02\x01@\x02\x04algo\x01\x05level}\0\x04\x04\0\x17[constructor]c\
ompressor\x01\x05\x01h\x02\x01p}\x01j\x01\x07\x01s\x01@\x02\x04self\x06\x05input\
\x07\0\x08\x04\0\x1b[method]compressor.compress\x01\x09\x01i\x03\x01@\x01\x04alg\
o\x01\0\x0a\x04\0\x19[constructor]decompressor\x01\x0b\x01h\x03\x01@\x02\x04self\
\x0c\x05input\x07\0\x08\x04\0\x1f[method]decompressor.decompress\x01\x0d\x01p\x01\
\x01@\0\0\x0e\x04\0\x14supported-algorithms\x01\x0f\x01ks\x01@\x01\x04algo\x01\0\
\x10\x04\0\x0ealgorithm-info\x01\x11\x04\0>tegmentum:compression-multiplexer/com\
pression-dispatcher@0.1.0\x05\0\x04\0?tegmentum:compression-multiplexer/compress\
ion-multiplexer@0.1.0\x04\0\x0b\x1d\x01\0\x17compression-multiplexer\x03\0\0\0G\x09\
producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.241.2\x10wit-bindgen-rus\
t\x060.48.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

